services:
  optiqra-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: optiqra-dev
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - optiqra-network
    command: npm run dev

networks:
  optiqra-network:
    driver: bridge
