# .github/workflows/release.yml
name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            args: "--target aarch64-apple-darwin"
          - os: macos-latest
            args: "--target x86_64-apple-darwin"
          - os: windows-latest
            args: ""
          - os: ubuntu-latest
            args: ""

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}